### PR TITLE
Update Tax integration (batch 1)

### PR DESCRIPTION
**Pull request by cecilphillip**
Updated samples for the following languages

- Node
- Python
- C#

### CODE REVIEW

**Comment by hideokamoto-stripe** [comment]
Nice @cecilphillip !
What do you think about moving the Tax flag into `.env` file?

e.g.(nodejs)
```diff
- const calculateTax = false;
+ const calculateTax = process.env.ENABLE_STRIPE_TAX ?? false;
```

We can easy to switch this just updating the `.env` file:
```
ENABLE_STRIPE_TAX=true 
```

**Comment by cecilphillip** [comment]
I thought about it but I didn't want to keep adding to the .env file. Do you think that would be better??

**Comment by hideokamoto-stripe** [comment]
@cecilphillip 
I think it's just a sample, so either method of implementation should be fine. 
However, if @hirabiya-san wants to also test the behavior of Tax within the CI/CD flow they are building and maintaining, using `.env` might be better. 

I don't think there's a need for such rigorous testing, but I wanted to double check just in case.

**Comment by cecilphillip** [comment]
@hideokamoto-stripe Who is @hirabiya-san?

**Comment by hideokamoto-stripe** [comment]
@cecilphillip 
FYI:@hibariya-san is one of the active contributors. He is a volunteer who is contributing to our sample repository by developing and maintaining our CI workflow.
https://github.com/stripe-samples/accept-a-payment/graphs/contributors

**Review by hideokamoto-stripe — APPROVED** [review]
LGTM!
Shall I update the PHP example after merge this?
@cecilphillip

**Comment by cecilphillip** [comment]
@hideokamoto-stripe we'll need updates for java, php and go. I can try to handle the Golang one

**Review by cecilphillip-stripe — APPROVED** [review]
LGTM

**Pull request merged**
