### PR TITLE
Sepa debit seems taking longer time than before to complete

### PR DESCRIPTION
**Pull request by hibariya**
I changed to fetch the status another couple of times.

Could anyone who has permission to write to this repository re-run this Ci? :pray: 
-> https://github.com/stripe-samples/accept-a-payment/actions/runs/5296454890/jobs/9587581633?pr=1819

### CODE REVIEW

**Comment by hideokamoto-stripe** [comment]
Hi @hibariya -san!
I quick checked this action and looks good.
スクリーンショット 2023-06-20 9 39 08

**Comment by user280920** [comment]
Gana hasta $8Peso por participar en las ofertas especiales del fin de
semana. https://vm.tiktok.com/ZM2DHffcD/

**Comment by hibariya** [comment]
@paulasjes-stripe Could you retry this job https://github.com/stripe-samples/accept-a-payment/actions/runs/5372096085/jobs/9745274555?pr=1819 when convenient? I increased the retry count. Thank you 🙏

**Comment by paulasjes-stripe** [comment]
I get a 500 error when trying to re-run the job. I'll try again later.

**Comment by Metamiddlelyzer** [comment]
Hi Paul,Can you give more details on what payment is this related to?Regards,SivaSent from my iPhoneOn 26 Jun 2023, at 4:16 PM, Paul Asjes ***@***.***> wrote:﻿
I get a 500 error when trying to re-run the job. I'll try again later.

**Comment by paulasjes-stripe** [comment]
@Metamiddlelyzer this is a test of the CI actions we've set up for this sample. No actual payments are affected.

**Comment by paulasjes-stripe** [comment]
@hibariya Looks like it worked!

**Comment by Metamiddlelyzer** [comment]
My prayers worked i guess 😇Sent from my iPhoneOn 27 Jun 2023, at 6:39 PM, Paul Asjes ***@***.***> wrote:﻿
@hibariya Looks like it worked!

**Pull request merged**
