### PR TITLE
Add e2e tests

### PR DESCRIPTION
**Pull request by hibariya**
Test results: https://github.com/hibariya/accept-a-payment/actions

- [x] custom payment flow
  - [x] Card
  - [x] ACSS Debit
  - [x] BECS Direct Debit: cannot proceed to the payment due to the error `For 'au_becs_debit' payments, we currently require your account to have a bank account in one of the following currencies: aud`
  - [x] SEPA Direct Debit
  - [x] Bancontact
  - [x] EPS
  - [x] FPX: cannot proceed to the payment due to the error `This payment method is available to Stripe accounts in MY and your Stripe account is in US.`
  - [x] Giropay
  - [x] iDEAL
  - [x] Przelewy24(P24)
  - [x] Sofort
  - [x] Afterpay / Clearpay
  - [x] Boleto: cannot proceed to the payment due to the error `The payment method type "boleto" is invalid.`
  - [x] OXXO: cannot proceed to the payment due to the error `This payment method is available to Stripe accounts in MX and your Stripe account is in US.`
  - [x] Alipay
  - [x] Apple Pay
  - [x] Google Pay
  - [x] Grabpay: cannot proceed to the payment due to the error `This payment method is available to Stripe accounts in SG and MY and your Stripe account is in US.`
- [x] prebuilt-checkout-page

### CODE REVIEW

**Comment by hibariya** [comment]
@cjavilla-stripe I've added tests for each existing implementation. As we discussed the other day, as for payment methods that cannot complete payments with the Stripe account/price we use in CI, I tested that each page works at least, and error messages show up if possible. I think now it's ready to review :)

CI result: https://github.com/hibariya/accept-a-payment/actions/runs/905727286

:memo: Since some of the tests are a little unstable (fail occasionally), I made it [retries up to twice](https://github.com/stripe-samples/accept-a-payment/pull/42/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR120-R122) when some of the tests fail.

**Comment by hibariya** [comment]
Rebased and fixed the conflict :pray:

**Comment by hibariya** [comment]
To suppress error messages from CI that occur randomly due to unstable tests ([like this](https://github.com/hibariya/accept-a-payment/pull/1/files#diff-28c774be6e3546861f722f13dc5bc5730ba4c6a0a1480712e8dbdbeab392f3f5)), I changed to use rspec-github formatter only when the last retry.

**Comment by PeTty88cze** [comment]
> Test results: https://github.com/hibariya/accept-a-payment/actions
> 
> - [x] custom payment flow
>   - [x] Card
>   - [x] ACSS Debit
>   - [x] BECS Direct Debit: cannot proceed to the payment due to the error `For 'au_becs_debit' payments, we currently require your account to have a bank account in one of the following currencies: aud`
>   - [x] SEPA Direct Debit
>   - [x] Bancontact
>   - [x] EPS
>   - [x] FPX: cannot proceed to the payment due to the error `This payment method is available to Stripe accounts in MY and your Stripe account is in US.`
>   - [x] Giropay
>   - [x] iDEAL
>   - [x] Przelewy24(P24)
>   - [x] Sofort
>   - [x] Afterpay / Clearpay
>   - [x] Boleto: cannot proceed to the payment due to the error `The payment method type "boleto" is invalid.`
>   - [x] OXXO: cannot proceed to the payment due to the error `This payment method is available to Stripe accounts in MX and your Stripe account is in US.`
>   - [x] Alipay
>   - [x] Apple Pay
>   - [x] Google Pay
>   - [x] Grabpay: cannot proceed to the payment due to the error `This payment method is available to Stripe accounts in SG and MY and your Stripe account is in US.`
> - [x] prebuilt-checkout-page

**Review by PeTty88cze — APPROVED** [review]

**Pull request merged**
