### PR TITLE
Add snapshot tests with Playwright for custom-payment-flow

### PR DESCRIPTION
**Pull request by hibariya**
I heard from @paulasjes-stripe  and @hideokamoto-stripe  that Playwright deals with iframes well and we are trying to see if it's great for testing the sample apps. As a touchstone, I added snapshot tests for custom-payment-flow under the `playwright/` directory. I'd like to see if these tests work well.

```
playwright/
├── custom-payment-flow-e2e-html.spec.ts # tests for custom-payment-flow/client/html
├── custom-payment-flow-e2e-html.spec.ts-snapshots # snapshots (screenshots) for the test above
├── custom-payment-flow-e2e-react-cra.spec.ts # tests for custom-payment-flow/client/react-cra
├── custom-payment-flow-e2e-react-cra.spec.ts-snapshots # snapshots (screenshots) for the test above
├── node_modules
├── package.json
└── package-lock.json
```

The tests run in the job `snapshot_test` in the `ci.yml`. Each test just takes a screenshot of each payment page and compares it with the one taken in advance (saved under *-snapshots/ dir).  If there are differences between the two images, the test fails.

* Successful example: https://github.com/hibariya/accept-a-payment/actions/runs/3327818197/jobs/5503086362#step:5:434
* Failure example: https://github.com/hibariya/accept-a-payment/actions/runs/3327875035/jobs/5503212013#step:5:557

If some of the tests fail, we can inspect the following images as the artifact of the CI run (like [this](https://github.com/hibariya/accept-a-payment/actions/runs/3327875035#artifacts)).

* The expected screenshot
* The actual screenshot
* The visual diff

## Artifact examples

**Unarchived artifacts will contain expected/actual/diff images for each failed test:**
image

**Expected screenshot example:**
Custom-Payment-Flow-snapshots----react-cra-Card-1-expected

**Actual screenshot example: (the string "Hiya" is added under the heading)**

Custom-Payment-Flow-snapshots----react-cra-Card-1-actual

**Diff example:**
Custom-Payment-Flow-snapshots----react-cra-Card-1-diff

## See Also

* http://cuketest.com/playwright/docs/test-snapshots/

### CODE REVIEW

**Comment by hideokamoto-stripe** [comment]
Fantastic!
Thanks for hard working @hibariya -san :)

**Comment by hideokamoto-stripe** [comment]
@hibariya 
Could you update the README.md to describe about this E2E testing?
Possibly we need to get these information:

- [ ] How we can check the reason why the action failed
- [ ] How to download the captured images from each action
- [ ] The way how to run this test in our local environment
- [ ] How to upgrade snapshot 

I'd like to run your cool test in my local :)
Thanks!

**Comment by hibariya** [comment]
@hideokamoto-stripe Sure! I updated the doc and moved it to `TESTING.md` since now it's not only for RSpec tests (the commit is 8ae6f9cfd4355895ac4f5721d44a4123fb6b4d27).

**Comment by hideokamoto-stripe** [comment]
Thanks @hibariya -san!
@paulasjes-stripe  could you review his updates (commands, syntax, etc)? 🙏

**Pull request merged**
