### PR TITLE
Add devcontainers configurations for client samples

### PR DESCRIPTION
**Pull request by hibariya**
Continuation of https://github.com/stripe-samples/accept-a-payment/pull/1927. Hi, as we discussed before, I added devcontainers configurations for client apps. Since both the server and client app use NodeJS, we can run them in the same container. That means we don't need to launch another Codespace for the client app.

We can generate configuration for a sample client app like this:

```shell
git clone https://github.com/stripe-samples/sample-ci.git
cd .devcontainer
./generate.sh custom-payment-flow node ../../client/react-cra node:lts
```

### CODE REVIEW

**Comment by hideokamoto-stripe** [comment]
Thanks @hibariya -san, and sorry for delaying checking.

## Testing log

- Launch the dev container from the `devcontainers-frontend` branch
- `cd .devcontainer`
- `./generate.sh custom-payment-flow node ../../client/react-cra node:lts`

## Result:

```bash
+ source ../sample-ci/helpers.sh
./generate.sh: line 3: ../sample-ci/helpers.sh: No such file or directory
```

## Questions
Should we test it in the local environment?
If I need to correct the step running it on the CodeSpaces, please feel free to let me know.

**Comment by hibariya** [comment]
@hideokamoto-stripe Hi Hide san, thanks for reviewing!
Sorry for the lack of information. We need to clone the sample-ci repo on top of the repository first. I updated the steps in the description 🙏

**Comment by hideokamoto-stripe** [comment]
Thank you @hibariya -san and sorry for the delaying.
I got the error while running `./generate.sh`:

```bash
ln: failed to create symbolic link './.env': File exists
```

Should we update the setup command on the Codespaces like the following?:

**Preparation step**
```bash
cp .env.example .env
code .env
// Put your Stripe API keys
```

**Setup step**
```bash
git clone https://github.com/stripe-samples/sample-ci.git
cd .devcontainer
./generate.sh custom-payment-flow node ../../client/react-cra node:lts
```

**Running application step**
?

Thanks.

**Comment by hibariya** [comment]
@hideokamoto-stripe I couldn't reproduce the error on my env. Would you mind sharing the whole output of the `generate.sh`? 🙏

**Comment by hideokamoto-stripe** [comment]
@hibariya -san,
Here is the entire log of running the `generate.sh` command.
 
```bash
@hideokamoto-stripe ➜ /workspaces/accept-a-payment/.devcontainer (devcontainers-frontend) $ ./generate.sh custom-payment-flow node ../../client/react-cra node:lts
+ source ../sample-ci/helpers.sh
+ export SAMPLE=custom-payment-flow
+ SAMPLE=custom-payment-flow
+ export SERVER_TYPE=node
+ SERVER_TYPE=node
+ export STATIC_DIR=../../client/react-cra
+ STATIC_DIR=../../client/react-cra
+ export SERVER_IMAGE=node:lts
+ SERVER_IMAGE=node:lts
+ '[' ../../client/react-cra = ../../client/html ']'
+ export SERVER_TYPE=node
+ SERVER_TYPE=node
+ export SERVER_IMAGE=node:lts
+ SERVER_IMAGE=node:lts
++ basename ../../client/react-cra
+ export WORKING_DIR=custom-payment-flow/client/react-cra
+ WORKING_DIR=custom-payment-flow/client/react-cra
++ tr / -
++ echo custom-payment-flow/client/react-cra
+ CONFIG_DIR=custom-payment-flow-client-react-cra
+ mkdir -p custom-payment-flow-client-react-cra
+ cat devcontainer-template.json
+ envsubst '$WORKING_DIR'
+ cp docker-compose.override.yml custom-payment-flow-client-react-cra/docker-compose.override.yml
+ pushd custom-payment-flow-client-react-cra
/workspaces/accept-a-payment/.devcontainer/custom-payment-flow-client-react-cra /workspaces/accept-a-payment/.devcontainer
+ ln -sF ../../sample-ci .
+ install_docker_compose_settings_for_integration custom-payment-flow node ../../client/react-cra node:lts
+ export SAMPLE=custom-payment-flow
+ SAMPLE=custom-payment-flow
+ export SERVER_TYPE=node
+ SERVER_TYPE=node
+ export STATIC_DIR=../../client/react-cra
+ STATIC_DIR=../../client/react-cra
+ export SERVER_IMAGE=node:lts
+ SERVER_IMAGE=node:lts
++ basename ../../client/react-cra
+ export CLIENT_TYPE=react-cra
+ CLIENT_TYPE=react-cra
+ [[ -z node:lts ]]
+ compose_file=docker-compose-v2.yml
+ variables='${SAMPLE}${SERVER_TYPE}${STATIC_DIR}${CLIENT_TYPE}${SERVER_IMAGE}'
+ envsubst '${SAMPLE}${SERVER_TYPE}${STATIC_DIR}${CLIENT_TYPE}${SERVER_IMAGE}'
+ cat sample-ci/docker/docker-compose-v2.yml
+ rm -f sample-ci
+ ln -sF ../.env .
ln: failed to create symbolic link './.env': File exists
```


Would you mind to share us the step-by-step to launch the example application?

1. Launch Codespaces from GitHub.com
2. Run `xxx` command in the `./xxx` directory
3. ...

We'd like to make sure the step to reproduce and test this PR. Thanks

**Comment by hideokamoto-stripe** [comment]
Possibly ,we can pass the `generate.sh` by updating this line:

```diff
-ln -sF ../.env .
+ln -sf ../.env .
```

**Comment by hibariya** [comment]
Oh, you are right. I fixed it in [dfb7196](https://github.com/stripe-samples/accept-a-payment/pull/2001/commits/dfb71968b04ca5fdf26a5fd6b14e5a2c036abe84). Thanks @hideokamoto-stripe 🙏

**Comment by hideokamoto-stripe** [comment]
Thank you @hibariya -san!

I completed to run the `generate.sh` command:

```bash
$ ./generate.sh custom-payment-flow node ../../client/react-cra node:lts
+ source ../sample-ci/helpers.sh
+ export SAMPLE=custom-payment-flow
+ SAMPLE=custom-payment-flow
+ export SERVER_TYPE=node
+ SERVER_TYPE=node
+ export STATIC_DIR=../../client/react-cra
+ STATIC_DIR=../../client/react-cra
+ export SERVER_IMAGE=node:lts
+ SERVER_IMAGE=node:lts
+ '[' ../../client/react-cra = ../../client/html ']'
+ export SERVER_TYPE=node
+ SERVER_TYPE=node
+ export SERVER_IMAGE=node:lts
+ SERVER_IMAGE=node:lts
++ basename ../../client/react-cra
+ export WORKING_DIR=custom-payment-flow/client/react-cra
+ WORKING_DIR=custom-payment-flow/client/react-cra
++ echo custom-payment-flow/client/react-cra
++ tr / -
+ CONFIG_DIR=custom-payment-flow-client-react-cra
+ mkdir -p custom-payment-flow-client-react-cra
+ envsubst '$WORKING_DIR'
+ cat devcontainer-template.json
+ cp docker-compose.override.yml custom-payment-flow-client-react-cra/docker-compose.override.yml
+ pushd custom-payment-flow-client-react-cra
/workspaces/accept-a-payment/.devcontainer/custom-payment-flow-client-react-cra /workspaces/accept-a-payment/.devcontainer
+ ln -sF ../../sample-ci .
+ install_docker_compose_settings_for_integration custom-payment-flow node ../../client/react-cra node:lts
+ export SAMPLE=custom-payment-flow
+ SAMPLE=custom-payment-flow
+ export SERVER_TYPE=node
+ SERVER_TYPE=node
+ export STATIC_DIR=../../client/react-cra
+ STATIC_DIR=../../client/react-cra
+ export SERVER_IMAGE=node:lts
+ SERVER_IMAGE=node:lts
++ basename ../../client/react-cra
+ export CLIENT_TYPE=react-cra
+ CLIENT_TYPE=react-cra
+ [[ -z node:lts ]]
+ compose_file=docker-compose-v2.yml
+ variables='${SAMPLE}${SERVER_TYPE}${STATIC_DIR}${CLIENT_TYPE}${SERVER_IMAGE}'
+ cat sample-ci/docker/docker-compose-v2.yml
+ envsubst '${SAMPLE}${SERVER_TYPE}${STATIC_DIR}${CLIENT_TYPE}${SERVER_IMAGE}'
+ rm -f sample-ci
+ ln -sf ../.env .
+ popd
/workspaces/accept-a-payment/.devcontainer
@hideokamoto-stripe ➜ /workspaces/accept-a-payment/.devcontainer (devcontainers-frontend) $ 
```

I'm curious about what should we do for the next?
Thanks.

**Pull request merged**
